- name: join client to domain
  hosts: vie-it-cli5
  gather_facts: false
  tasks:

    - name: join host to SVAL.at with automatic reboot
      microsoft.ad.membership:
        dns_domain_name: SVAL.at
        domain_admin_user: Administrator@SVAL.at
        domain_admin_password: Supergeheim123!
        state: domain
        reboot: true