- name: Administrator Concept
  hosts: dc1
  gather_facts: no
  tasks:

    - name: Create a new Domain Admin (admin)
      microsoft.ad.user:
        name: admin
        password: Ganzgeheim123!
        groups:
          set:
            - Domain Users
            - Domain Admins
        state: present
        description: "Domain Admin user account"

    - name: Create a new Enterprise Admin and Schema Admin (superadmin)
      microsoft.ad.user:
        name: superadmin
        password: Ganzgeheim123!
        groups:
          set:
            - Domain Users
            - Enterprise Admins
            - Schema Admins
        state: present
        description: "Enterprise Admin and Schema Admin user account"