- name: Change FSMO Roles
  hosts: dc1
  gather_facts: no
  tasks:

    - name: Transfer RID Master role to DC2
      ansible.windows.win_shell: |
        Move-ADDirectoryServerOperationMasterRole -Identity "dc2" -OperationMasterRole "RIDMaster" -Confirm:$false

    - name: Transfer PDC Emulator role to DC2
      ansible.windows.win_shell: |
        Move-ADDirectoryServerOperationMasterRole -Identity "dc2" -OperationMasterRole "PDCEmulator" -Confirm:$false

    - name: Transfer Infrastructure Master role to DC2
      ansible.windows.win_shell: |
        Move-ADDirectoryServerOperationMasterRole -Identity "dc2" -OperationMasterRole "InfrastructureMaster" -Confirm:$false