- name: Create JEA groups, users and OUs in Active Directory
  hosts: dc1
  gather_facts: no
  tasks:

    - name: Create "Admins" Organizational Unit in Wien
      win_ad_organizational_unit:
        name: Admins
        path: "OU=Wien,DC=SVAL,DC=at"
        state: present

    - name: Create "Users" Organizational Unit in Admins
      win_ad_organizational_unit:
        name: Users
        path: "OU=Admins,OU=Wien,DC=SVAL,DC=at"
        state: present

    - name: Create the JEA groups in Users OU
      win_ad_group:
        name: "{{ item }}"
        path: "OU=Users,DC=SVAL,DC=at"
        state: present
      loop:
        - Server Admins
        - User Admins
        - Network Admins
        - Security Admins
        - Backup Admins

    - name: Create User 'Paul Wagner'
      win_user:
        name: paul.wagner
        password: ServerAdmin@Paul2024!
        groups:
          - Server Admins
          - Domain Users
        state: present
        path: "OU=Users,OU=Admins,OU=Wien,DC=SVAL,DC=at"

    - name: Create User 'Sarah Müller'
      win_user:
        name: sarah.mueller
        password: UserAdmin@Sarah2024!
        groups:
          - User Admins
          - Domain Users
        state: present
        path: "OU=Users,OU=Admins,OU=Wien,DC=SVAL,DC=at"

    - name: Create User 'Michael Bauer'
      win_user:
        name: michael.bauer
        password: NetworkAdmin@Michael2024!
        groups:
          - Network Admins
          - Domain Users
        state: present
        path: "OU=Users,OU=Admins,OU=Wien,DC=SVAL,DC=at"

    - name: Create User 'Eva Richter'
      win_user:
        name: eva.richter
        password: Security@Eva2024!
        groups:
          - Security Admins
          - Domain Users
        state: present
        path: "OU=Users,OU=Admins,OU=Wien,DC=SVAL,DC=at"

    - name: Create User 'Tom Zimmermann'
      win_user:
        name: tom.zimmermann
        password: BackupAdmin@Tom2024!
        groups:
          - Backup Admins
          - Domain Users
        state: present
        path: "OU=Users,OU=Admins,OU=Wien,DC=SVAL,DC=at"

    - name: Create User 'Monika König'
      win_user:
        name: monika.koenig
        password: BackupAdmin@Monika2024!
        groups:
          - Backup Admins
          - Domain Users
        state: present
        path: "OU=Users,OU=Admins,OU=Wien,DC=SVAL,DC=at"
