- name: Create JEA groups, users and OUs in Active Directory
  hosts: dc1
  gather_facts: no
  tasks:

    - name: Create "Admins" Organizational Unit in Wien
      microsoft.ad.ou:
        name: Admins
        path: "OU=Wien,DC=SVAL,DC=at"
        state: present

    - name: Create "Users" Organizational Unit in Admins
      microsoft.ad.ou:
        name: Users
        path: "OU=Admins,OU=Wien,DC=SVAL,DC=at"
        state: present

    - name: Create the JEA groups in Users OU
      microsoft.ad.group:
        name: "{{ item }}"
        scope: global
        state: present
      loop:
        - Server Admins
        - User Admins
        - Network Admins
        - Security Admins
        - Backup Admins

    - name: Create User 'Paul Wagner'
      microsoft.ad.user:
        name: paul.wagner
        firstname: Paul
        surname: Wagner
        password: ServerAdmin@Paul2024!
        password_never_expires: yes
        groups:
          set:
            - Server Admins
            - Domain Users
        path: "OU=Users,OU=Admins,OU=Wien,DC=SVAL,DC=at"
        state: present

    - name: Create User 'Sarah Müller'
      microsoft.ad.user:
        name: sarah.mueller
        firstname: Sarah
        surname: Müller
        password: UserAdmin@Sarah2024!
        password_never_expires: yes
        groups:
          set:
            - User Admins
            - Domain Users
        path: "OU=Users,OU=Admins,OU=Wien,DC=SVAL,DC=at"
        state: present

    - name: Create User 'Michael Bauer'
      microsoft.ad.user:
        name: michael.bauer
        firstname: Michael
        surname: Bauer
        password: NetworkAdmin@Michael2024!
        password_never_expires: yes
        groups:
          set:
            - Network Admins
            - Domain Users
        path: "OU=Users,OU=Admins,OU=Wien,DC=SVAL,DC=at"
        state: present

    - name: Create User 'Eva Richter'
      microsoft.ad.user:
        name: eva.richter
        firstname: Eva
        surname: Richter
        password: Security@Eva2024!
        password_never_expires: yes
        groups:
          set:
            - Security Admins
            - Domain Users
        path: "OU=Users,OU=Admins,OU=Wien,DC=SVAL,DC=at"
        state: present

    - name: Create User 'Tom Zimmermann'
      microsoft.ad.user:
        name: tom.zimmermann
        firstname: Tom
        surname: Zimmermann
        password: BackupAdmin@Tom2024!
        password_never_expires: yes
        groups:
          set:
            - Backup Admins
            - Domain Users
        path: "OU=Users,OU=Admins,OU=Wien,DC=SVAL,DC=at"
        state: present

    - name: Create User 'Monika König'
      microsoft.ad.user:
        name: monika.koenig
        firstname: Monika
        surname: König
        password: BackupAdmin@Monika2024!
        password_never_expires: yes
        groups:
          set:
            - Backup Admins
            - Domain Users
        path: "OU=Users,OU=Admins,OU=Wien,DC=SVAL,DC=at"
        state: present