- name: Create AD OU Structure
  hosts: dc1
  gather_facts: no
  tasks:
    - name: Create top-level OU - Wien
      microsoft.ad.ou:
        name: Wien
        path: "DC=SVAL,DC=at"
        state: present

    - name: Create sub-OUs under Wien
      loop:
        - IT
        - Sales
        - HR
      microsoft.ad.ou:
        name: "{{ item }}"
        path: "OU=Wien,DC=SVAL,DC=at"
        state: present

    - name: Create child OUs under Wien/IT
      loop:
        - Users
        - Computers
        - Resources
        - Special
      microsoft.ad.ou:
        name: "{{ item }}"
        path: "OU=IT,OU=Wien,DC=SVAL,DC=at"
        state: present

    - name: Create child OUs under Wien/Sales
      loop:
        - Users
        - Computers
        - Resources
        - Special
      microsoft.ad.ou:
        name: "{{ item }}"
        path: "OU=Sales,OU=Wien,DC=SVAL,DC=at"
        state: present

    - name: Create child OUs under Wien/HR
      loop:
        - Users
        - Computers
        - Resources
        - Special
      microsoft.ad.ou:
        name: "{{ item }}"
        path: "OU=HR,OU=Wien,DC=SVAL,DC=at"
        state: present

    - name: Create top-level OU - Linz
      microsoft.ad.ou:
        name: Linz
        path: "DC=SVAL,DC=at"
        state: present

    - name: Create sub-OU under Linz
      microsoft.ad.ou:
        name: Development
        path: "OU=Linz,DC=SVAL,DC=at"
        state: present

    - name: Create child OUs under Linz/Development
      loop:
        - Users
        - Computers
        - Resources
        - Special
      microsoft.ad.ou:
        name: "{{ item }}"
        path: "OU=Development,OU=Linz,DC=SVAL,DC=at"
        state: present
