---
  - name: Grundkonfiguration vie-it-cli6
    hosts: vie-it-cli6
    gather_facts: no
    tasks:

      - name: Set Hostname
        ansible.windows.win_hostname:
          name: vie-it-cli6

      - name: Set Interface Name
        ansible.windows.win_shell: |
          Get-NetAdapter | Rename-NetAdapter -NewName "VIE_IT_CLI"
      
      - name: Set DNS
        ansible.windows.win_shell: |
          Set-DnsClientServerAddress -InterfaceAlias "VIE_IT_CLI" -ServerAddresses ("10.2.1.1", "10.2.1.2")

      - name: Set Timezone
        ansible.windows.win_shell: |
          Set-TimeZone -Id "W. Europe Standard Time"

      - name: Set Timezone
        ansible.windows.win_shell: |
          Set-NetFirewallRule -Name "FPS-ICMP4-ERQ-In" -Enabled True
          Set-NetFirewallRule -Name "FPS-ICMP4-ERQ-Out" -Enabled True
      
      - name: Enable PS-Remoting
        ansible.windows.win_shell: |
          Enable-PSRemoting -Force

      - name: Reboot
        ansible.windows.win_reboot:
