- name: Initial Configuration lnz-dev-cli3
  hosts: lnz-dev-cli3
  gather_facts: no
  tasks:

    - name: Set Hostname
      ansible.windows.win_hostname:
        name: lnz-dev-cli3

    - name: Set Interface Name
      ansible.windows.win_shell: |
        Get-NetAdapter | Rename-NetAdapter -NewName "LNZ_DEV_CLI"
    
    - name: Set DNS
      ansible.windows.win_shell: |
        Set-DnsClientServerAddress -InterfaceAlias "LNZ_DEV_CLI" -ServerAddresses ("10.2.1.1", "10.2.1.2")

    - name: Set Timezone
      ansible.windows.win_shell: |
        Set-TimeZone -Id "W. Europe Standard Time"

    - name: Set Private Network
      ansible.windows.win_shell: |
        Set-NetConnectionProfile -InterfaceAlias "LNZ_DEV_CLI" -NetworkCategory "Private"

    - name: Set Firewall Rules
      ansible.windows.win_shell: |
        Set-NetFirewallRule -Name "FPS-ICMP4-ERQ-In" -Enabled True -Profile Domain,Private
        Set-NetFirewallRule -Name "FPS-ICMP4-ERQ-Out" -Enabled True -Profile Domain,Private
    
    - name: Enable PS-Remoting
      ansible.windows.win_shell: |
        Enable-PSRemoting -Force

    - name: Enable Remote Desktop
      ansible.windows.win_shell: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -value 0
    
    - name: Enable Remote Desktop Firewall Rule
      ansible.windows.win_shell: |
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop" 

    - name: Reboot
      ansible.windows.win_reboot: