---
- name: Konfiguriere persistente IP-Adresse auf einem Linux-Client
  hosts: vie-open-vswitch
  become: yes  # Damit werden root-Rechte verwendet
  vars_prompt:
    - name: "hostname"
      prompt: "Bitte geben Sie den Hostnamen für den Switch ein"
      private: no  # Setze auf 'yes', falls die Eingabe nicht sichtbar sein soll
  tasks:
    - name: Set the system hostname
      ansible.builtin.hostname:
        name: "{{ hostname }}"

    - name: Update /etc/hosts with new hostname
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: "^127\\.0\\.1\\.1"
        line: "127.0.1.1 {{ hostname }}"
        state: present

    - name: Überprüfe, ob Netplan-Datei existiert
      stat:
        path: /etc/netplan/50-cloud-init.yaml
      register: netplan_config

    - name: Konfiguriere statische IP-Adresse mit Netplan
      copy:
        content: |
          network:
              version: 2
              ethernets:
                ens33:
                  dhcp4: true
                  match:
                    macaddress: 00:50:56:bc:e0:63
                  set-name: outside
                VIE_to_Serv:
                  match:
                    macaddress: 00:50:56:bc:b0:26
                  set-name: VIE_to_Serv_209
                VIE_201_Serv:
                  match:
                    macaddress: 00:50:56:BC:E1:FF
                  addresses:
                    - 10.2.0.1/30
                  set-name: VIE_201_Serv_HR
                ens33:
                  addresses:
                    - 172.16.1.1/24
                  match:
                    macaddress: 00:50:56:bc:57:15
                  set-name: Extra_mgmt
        dest: /etc/netplan/50-cloud-init.yaml
        mode: '0644'

    - name: Wende Netplan-Konfiguration an
      command: netplan apply

    - name: Reboot the switch to apply all changes
      ansible.builtin.reboot:
        reboot_timeout: 300