---
- name: Configure Open vSwitch
  hosts: vie-open-vswitch
  become: true
  tasks:
    - name: Update apt package list
      ansible.builtin.apt:
        update_cache: yes
        
    - name: Installiere FRR und FRR-Pythontools
      ansible.builtin.command:
        cmd: sudo apt install -y frr frr-pythontools

    - name: Bearbeite die Datei /etc/frr/daemons, um OSPF zu aktivieren
      ansible.builtin.replace:
        path: /etc/frr/daemons
        regexp: '^ospfd=no'
        replace: 'ospfd=yes'
        backup: yes

    - name: Überprüfe die Datei /etc/frr/daemons
      ansible.builtin.command:
        cmd: cat /etc/frr/daemons
      register: daemons_file_content

    - name: Gib die Inhalte der Datei /etc/frr/daemons aus (Debugging)
      ansible.builtin.debug:
        var: daemons_file_content.stdout_lines
    
    - name: OSPF konfig über vtsyh
      ansible.builtin.shell:
        cmd: |
          vtysh -c "configure terminal" \
                -c "router ospf" \
                -c "network 10.2.1.0/29 area 10" \
                -c "network 10.2.2.0/29 area 10" \
                -c "network 10.2.3.0/29 area 10" \
                -c "router-id 10.2.0.1" \
                -c "exit" \
                -c "do write"

    - name: Ausgabe die Datei /etc/frr/frr.conf
      ansible.builtin.command:
        cmd: cat /etc/frr/frr.conf
      register: daemons_file_content

    - name: Gib die Inhalte der Datei /etc/frr/frr.conf aus (Debugging)
      ansible.builtin.debug:
        var: daemons_file_content.stdout_lines

    - name: Starte den FRR-Dienst neu
      ansible.builtin.systemd:
        name: frr
        state: restarted
        enabled: yes

    - name: Zeige den Status des FRR-Dienstes
      ansible.builtin.command:
        cmd: sudo systemctl status frr
      register: frr_status

    - name: Gib den Status des FRR-Dienstes aus
      ansible.builtin.debug:
        var: frr_status.stdout_lines