- name: Change DNS back to own DNS
  hosts: dc2
  gather_facts: no
  tasks:

    - name: Set DNS
      ansible.windows.win_shell: |
        Set-DnsClientServerAddress -InterfaceAlias "VIE_InfraSrv" -ServerAddresses ("10.2.1.2", "10.2.1.1")