---
  - name: Promote to Domain Controller and Join Domain
    hosts: dc2
    gather_facts: no
    tasks:

      - name: Install Active Directory Domain Services and DNS Server roles
        win_feature:
          name: 
            - AD-Domain-Services
            - DNS
          state: present

      - name: Promote server to Domain Controller and Join
        microsoft.ad.domain_controller:
          dns_domain_name: SVAL.at
          domain_admin_user: SVAL\Administrator
          domain_admin_password: Supergeheim123!
          safe_mode_password: Supergeheim123!
          state: domain_controller
          sysvol_path: C:\Windows\SYSVOL
          database_path: C:\Windows\NTDS
          domain_log_path: C:\Windows\NTDS
        register: dc_promotion

      - name: Reboot after promotion
        ansible.windows.win_reboot:
        when: dc_promotion.reboot_required
