- name: Set homeDirectory for Users via PowerShell
  hosts: dc2
  gather_facts: no
  tasks:

    - name: Set homeDirectory for Max Müller
      ansible.windows.win_shell: |
        Set-ADUser -Identity max.mueller -HomeDirectory "\\DC2\userhome$\%username%" -HomeDrive U:

    - name: Set homeDirectory for Lukas Schmidt
      ansible.windows.win_shell: |
        Set-ADUser -Identity lukas.schmidt -HomeDirectory "\\DC2\userhome$\%username%" -HomeDrive U:

    - name: Set homeDirectory for Jan Fischer
      ansible.windows.win_shell: |
        Set-ADUser -Identity jan.fischer -HomeDirectory "\\DC2\userhome$\%username%" -HomeDrive U:

    - name: Set homeDirectory for Anna Weber
      ansible.windows.win_shell: |
        Set-ADUser -Identity anna.weber -HomeDirectory "\\DC2\userhome$\%username%" -HomeDrive U:

    - name: Set homeDirectory for Paul Meyer
      ansible.windows.win_shell: |
        Set-ADUser -Identity paul.meyer -HomeDirectory "\\DC2\userhome$\%username%" -HomeDrive U:

    - name: Set homeDirectory for Sarah Becker
      ansible.windows.win_shell: |
        Set-ADUser -Identity sarah.becker -HomeDirectory "\\DC2\userhome$\%username%" -HomeDrive U:

    - name: Set homeDirectory for Laura Wagner
      ansible.windows.win_shell: |
        Set-ADUser -Identity laura.wagner -HomeDirectory "\\DC2\userhome$\%username%" -HomeDrive U:

    - name: Set homeDirectory for Tim Schneider
      ansible.windows.win_shell: |
        Set-ADUser -Identity tim.schneider -HomeDirectory "\\DC2\userhome$\%username%" -HomeDrive U:

    - name: Set homeDirectory for Julia Hoffmann
      ansible.windows.win_shell: |
        Set-ADUser -Identity julia.hoffmann -HomeDirectory "\\DC2\userhome$\%username%" -HomeDrive U:

    - name: Set homeDirectory for Eva Bauer
      ansible.windows.win_shell: |
        Set-ADUser -Identity eva.bauer -HomeDirectory "\\DC2\userhome$\%username%" -HomeDrive U:

    - name: Set homeDirectory for Markus Schmidt
      ansible.windows.win_shell: |
        Set-ADUser -Identity markus.schmidt -HomeDirectory "\\DC2\userhome$\%username%" -HomeDrive U: