- name: Set homeDirectory for Users via PowerShell
  hosts: dc2
  gather_facts: no
  vars:
    users:
      - name: max.mueller
      - name: lukas.schmidt
      - name: jan.fischer
      - name: anna.weber
      - name: paul.meyer
      - name: sarah.becker
      - name: laura.wagner
      - name: tim.schneider
      - name: julia.hoffmann
      - name: eva.bauer
      - name: markus.schmidt
      - name: lena.schulz
      - name: simon.braun
      - name: anna.richter
      - name: tobias.zimmermann
      
  tasks:
    - name: Set homeDirectory for each user
      ansible.windows.win_shell: |
        Set-ADUser -Identity {{ item.name }} -HomeDirectory "\\DC2\userhome$\{{ item.name }}" -HomeDrive U:
      loop: "{{ users }}"