---
- name: Initial configuration for DC1
  import_playbook: dc1/initial_config.yml

- name: Initial configuration for DC2
  import_playbook: dc2/initial_config.yml

- name: Initial configuration for VIE-IT-CLI1
  import_playbook: vie-it-cli1/initial_config.yml

- name: Initial configuration for VIE-IT-CLI2
  import_playbook: vie-it-cli2/initial_config.yml

- name: Initial configuration for VIE-IT-CLI3
  import_playbook: vie-it-cli3/initial_config.yml

- name: Initial configuration for VIE-IT-CLI4
  import_playbook: vie-it-cli4/initial_config.yml

- name: Initial configuration for VIE-IT-CLI5
  import_playbook: vie-it-cli5/initial_config.yml

- name: Initial configuration for VIE-IT-CLI6
  import_playbook: vie-it-cli6/initial_config.yml
