- name: Grundkonfiguration lnz-dev-cli1
  hosts: lnz-dev-cli1
  gather_facts: no
  tasks:

    - name: Set Hostname
      ansible.windows.win_hostname:
        name: lnz-dev-cli1

    - name: Set Interface Name
      ansible.windows.win_shell: |
        Get-NetAdapter | Rename-NetAdapter -NewName "LNZ_DEV_CLI"
    
    - name: Set DNS
      ansible.windows.win_shell: |
        Set-DnsClientServerAddress -InterfaceAlias "LNZ_DEV_CLI" -ServerAddresses ("10.2.1.1", "10.2.1.2")

    - name: Set Timezone
      ansible.windows.win_shell: |
        Set-TimeZone -Id "W. Europe Standard Time"

    - name: Set Firewall Rules
      ansible.windows.win_shell: |
        Set-NetFirewallRule -Name "FPS-ICMP4-ERQ-In" -Enabled True
        Set-NetFirewallRule -Name "FPS-ICMP4-ERQ-Out" -Enabled True
    
    - name: Enable PS-Remoting
      ansible.windows.win_shell: |
        Enable-PSRemoting -Force

    - name: Reboot
      ansible.windows.win_reboot: