- name: join vie-hr-cli1 to domain
  hosts: vie-hr-cli1
  gather_facts: false
  tasks:

    - name: join host to SVAL.at with automatic reboot
      microsoft.ad.membership:
        dns_domain_name: SVAL.at
        domain_admin_user: Administrator@SVAL.at
        domain_admin_password: Supergeheim123!
        domain_ou_path: "OU=Computers,OU=HR,OU=Wien,DC=SVAL,DC=at"
        state: domain
        reboot: true